services:

  api:
    container_name: hr-api-${BUILD:-prod}
    image: "ghcr.io/jordyegnl/hr-applicatie:${TAG:-latest}"
    restart: always
    ports:
      - "${PORT:-80}:5000"
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: "3306"
      DB_NAME: "hr"
      DB_USER: ${DB_USER:-dbadmin}
      DB_PASSWORD: ${DB_PASSWORD:-dbadmin}
      API_DEBUG: ${API_DEBUG:-false}
      API_DEFAULT_USER: ${API_DEFAULT_USER:-admin}
      API_DEFAULT_PASSWORD: ${API_DEFAULT_PASSWORD:-password}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "127.0.0.1:5000/healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: hr-db-${BUILD:-prod}
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "hr"
      MYSQL_USER: "dbadmin"
      MYSQL_PASSWORD: "dbadmin"
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10