version: "3"

services:
  whoami:
    image: ghcr.io/jordyegnl/hr-applicatie:latest
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: "10s"
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx-prod.rule=Host(`hr.hoebergen.net`)" # Vervang door je domeinnaam
        - "traefik.http.routers.nginx-prod.service=nginx-prod"
        - "traefik.http.routers.nginx-prod.entrypoints=websecure"
        - "traefik.http.services.nginx-prod.loadbalancer.server.port=80"

networks:
  default:
    name: web
    external: true