version: "3"

services:
  whoami:
    image: ghcr.io/jordyegnl/hr-applicatie:staging
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: "10s"
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.nginx-staging.rule=Host(`staging.hr.hoebergen.net`)" # Vervang door je domeinnaam
        - "traefik.http.routers.nginx-staging.service=nginx-staging"
        - "traefik.http.routers.nginx-staging.entrypoints=websecure"
        - "traefik.http.services.nginx-staging.loadbalancer.server.port=80"

networks:
  default:
    name: web
    external: true