global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: DEBUG

serversTransport:
  insecureSkipVerify: true

entryPoints:
  # Not used in apps, but redirect everything from HTTP to HTTPS
  web:
    address: :80
    forwardedHeaders:
      trustedIPs: &trustedIps
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 173.245.48.0/20
        - 103.21.244.0/22
        - 103.22.200.0/22
        - 103.31.4.0/22
        - 141.101.64.0/18
        - 108.162.192.0/18
        - 190.93.240.0/20
        - 188.114.96.0/20
        - 197.234.240.0/22
        - 198.41.128.0/17
        - 162.158.0.0/15
        - 104.16.0.0/12
        - 172.64.0.0/13
        - 131.0.72.0/22
        - 2400:cb00::/32
        - 2606:4700::/32
        - 2803:f800::/32
        - 2405:b500::/32
        - 2405:8100::/32
        - 2a06:98c0::/29
        - 2c0f:f248::/32
    proxyProtocol:
      trustedIPs: *trustedIps
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  # HTTPS endpoint, with domain wildcard
  websecure:
    address: :443
    proxyProtocol:
      trustedIPs: *trustedIps
    forwardedHeaders:
      trustedIPs: *trustedIps
    http:
      tls:
        # Generate a wildcard domain certificate
        certResolver: letsencrypt
        domains:
          - main: hoebergen.net
            sans:
              - '*.hr.hoebergen.net'
              - 'hr.hoebergen.net'

api:
  dashboard: true
  insecure: true

providers:
  swarm:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Alleen services met expliciete labels worden blootgesteld
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: <jouwemail>
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare  # Vervang door jouw DNS-provider
        delayBeforeCheck: 10
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"