name: "Nightly - Build and Deploy"

on:
  schedule:
    - cron: "0 0 * * *" # Run every night at midnight
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4

      # Lint Dockerfile
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/Dockerfile

  DeployNightly:
    name: "Deploy to Nightly"
    needs: Lint
    runs-on: self-hosted
    environment:
      name: dev
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: | 
            nightly
            ${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy on Nightly infrastructure
        run: |
          echo "Deploying to nightly environment"
          echo "Deployed to ${{ job.environment.url }}"

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker compose and env files to nightly server
        run: |
          ssh -o StrictHostKeyChecking=no jordy@10.0.20.12 "mkdir -p /home/jordy/docker/hr-applicatie-nightly"
          scp -o StrictHostKeyChecking=no ./docker-compose-nightly.yml jordy@10.0.20.12:/home/jordy/docker/hr-applicatie-nightly/docker-compose.yml
          scp -o StrictHostKeyChecking=no ./nightly.env jordy@10.0.20.12:/home/jordy/docker/hr-applicatie-nightly/.env

      - name: Deploy stack to swarm
        run: |
          ssh -o StrictHostKeyChecking=no jordy@10.0.20.12 "cd /home/jordy/docker/hr-applicatie-nightly && docker stack deploy --compose-file docker-compose.yml nginx-nightly"