name: "Pull Request - Build and Deploy"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4

      # Lint Dockerfile
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/Dockerfile

  DeployPR:
    name: "Deployp to PR"
    if: github.event_name == 'pull_request'
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: | 
            pr-${{ github.event.pull_request.number }}
            ${{ github.sha }}
          labels: |
            source: ${{ github.event.pull_request.head.ref }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./src
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}